# Holiday Package Statement

## 1. Problem Statement

"Travel.Com" company wants to enable and establish a viable business model to expand the customer base. One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering - Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information. The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being.However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.

## 2. Data Collection

The dataset is Collected from: https://www.kaggle.com/datasets/susant4learning/holiday-package-purchase-prediction

License: CC0: Public Domain

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [2]:
df =pd.read_csv("dataset\Travel.csv")
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

## 3. Data CLeaning

1. Handle Missing Values
2. Handle Duplicates
3. Check data type
4. Understand dataset

In [3]:
# Get missing val stats

df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [4]:
# Let us extract the columns and their sum (missing val) and %

features_with_null=[features for features in df.columns if df[features].isnull().sum()>=1]

# print(len(df["Age"]))
# print(df["Age"].isnull().sum().astype(int))
# print(np.round(df["Age"].isnull().sum().astype(int)/len(df["Age"])*100,3))

for feature in features_with_null:
    print(f"Missing Value % in {feature}:",np.round(df[feature].isnull().sum().astype(int)/len(df[feature])*100,3),"%" , f"                  Data Type: {df[feature].dtype}", f"            Number of missing values: {df[feature].isnull().sum()}")

Missing Value % in Age: 4.624 %                   Data Type: float64             Number of missing values: 226
Missing Value % in TypeofContact: 0.511 %                   Data Type: object             Number of missing values: 25
Missing Value % in DurationOfPitch: 5.135 %                   Data Type: float64             Number of missing values: 251
Missing Value % in NumberOfFollowups: 0.921 %                   Data Type: float64             Number of missing values: 45
Missing Value % in PreferredPropertyStar: 0.532 %                   Data Type: float64             Number of missing values: 26
Missing Value % in NumberOfTrips: 2.864 %                   Data Type: float64             Number of missing values: 140
Missing Value % in NumberOfChildrenVisiting: 1.35 %                   Data Type: float64             Number of missing values: 66
Missing Value % in MonthlyIncome: 4.767 %                   Data Type: float64             Number of missing values: 233

In [5]:
def getMissingValueReport(df):
    features_with_null=[features for features in df.columns if df[features].isnull().sum()>=1]
    missing_data = []
    for feature in features_with_null:
        missing_data.append({
        'Feature Name': feature,
        'Data Type': df[feature].dtype,
        'Count': df[feature].isnull().sum(),
        '%': np.round(df[feature].isnull().sum().astype(int)/len(df[feature])*100, 3)
    })

    missingvalreport = pd.DataFrame(missing_data)
    print(missingvalreport)

## 4. Data Engineering

In [6]:
# Let us explore the categorical features.

df.dtypes

CustomerID                    int64
ProdTaken                     int64
Age                         float64
TypeofContact                object
CityTier                      int64
DurationOfPitch             float64
Occupation                   object
Gender                       object
NumberOfPersonVisiting        int64
NumberOfFollowups           float64
ProductPitched               object
PreferredPropertyStar       float64
MaritalStatus                object
NumberOfTrips               float64
Passport                      int64
PitchSatisfactionScore        int64
OwnCar                        int64
NumberOfChildrenVisiting    float64
Designation                  object
MonthlyIncome               float64
dtype: object

In [7]:
# Get only the object data types
df.dtypes[df.dtypes=="object"]

TypeofContact     object
Occupation        object
Gender            object
ProductPitched    object
MaritalStatus     object
Designation       object
dtype: object

In [8]:
df["TypeofContact"].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [9]:
df["Occupation"].value_counts()

Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64

In [10]:
df["Gender"].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [11]:
# There is a typo error, let us fix it.

df["Gender"]=df["Gender"].replace("Fe Male", "Female")
df["Gender"].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [12]:
df["ProductPitched"].value_counts()

ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64

In [13]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [14]:
# Single and umarried can be combined together.
df["MaritalStatus"]= df["MaritalStatus"].replace("Unmarried","Single")
df["MaritalStatus"].value_counts()

MaritalStatus
Married     2340
Single      1598
Divorced     950
Name: count, dtype: int64

In [15]:
df["Designation"].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

### Lets us see if the mean of the data varies too much from the 50% percentile for non-object dtypes --> if yes too much outliers.

In [16]:
df.drop(columns="CustomerID", inplace=True)

In [17]:
df.select_dtypes(exclude="object").dtypes

ProdTaken                     int64
Age                         float64
CityTier                      int64
DurationOfPitch             float64
NumberOfPersonVisiting        int64
NumberOfFollowups           float64
PreferredPropertyStar       float64
NumberOfTrips               float64
Passport                      int64
PitchSatisfactionScore        int64
OwnCar                        int64
NumberOfChildrenVisiting    float64
MonthlyIncome               float64
dtype: object

In [18]:
df.select_dtypes(exclude="object").describe()

,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [19]:
getMissingValueReport(df)

               Feature Name Data Type  Count      %
0                       Age   float64    226  4.624
1             TypeofContact    object     25  0.511
2           DurationOfPitch   float64    251  5.135
3         NumberOfFollowups   float64     45  0.921
4     PreferredPropertyStar   float64     26  0.532
5             NumberOfTrips   float64    140  2.864
6  NumberOfChildrenVisiting   float64     66  1.350
7             MonthlyIncome   float64    233  4.767

#### For < 2% missing data we can employ Mode Imputation and for >2% median.

In [20]:
# df.TypeofContact.mode()[0]

In [21]:
# Handling >2%
df.Age.fillna(df.Age.median(),inplace=True)
df.DurationOfPitch.fillna(df.DurationOfPitch.median(), inplace=True)
df.NumberOfTrips.fillna(df.NumberOfTrips.median(), inplace=True)
df.MonthlyIncome.fillna(df.MonthlyIncome.median(), inplace=True)


#Handling <2%
df.TypeofContact.fillna(df.TypeofContact.mode()[0], inplace=True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0], inplace=True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0], inplace=True)
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0], inplace=True)

In [22]:
df.isnull().sum()

ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

## 5. Study The Features [ Feature Enginnering ]

In [23]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

We have 2 columns: NumberOfPersonVisiting , NumberOfChildrenVisiting.
Can be combined into one column

In [24]:
df["TotalVisitors"]= df["NumberOfPersonVisiting"]+df["NumberOfChildrenVisiting"]
df.drop(columns=["NumberOfPersonVisiting","NumberOfChildrenVisiting"], axis=1, inplace=True)
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisitors
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [25]:
# Get total number of numeric Features:
num_features=df.select_dtypes(exclude="object").columns.tolist()
print("Total Numeric Features: ", len(df.select_dtypes(exclude="object").columns.tolist()))

Total Numeric Features:  12

In [26]:
# Get total number of categorical Features:
cat_features=df.select_dtypes("object").columns.tolist()
print("Total Categorical Features: ", len(df.select_dtypes("object").columns.tolist()))

Total Categorical Features:  6

In [27]:
# Discreate Numerical Features.
discrete_feature=[feature for feature in num_features if len(df[feature].unique())<=25]
print("Number of Numerical Discreate Features", len(discrete_feature))

Number of Numerical Discreate Features 9

In [28]:
# Continuous Numerical Features
continuous_Feature=[feature for feature in num_features if len(df[feature].unique())>25]
print("Number of Numerical Continuous Features", len(continuous_Feature))

Number of Numerical Continuous Features 3

In [29]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisitors
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

## 6. Train Test Split and Model Training

In [30]:
from sklearn.model_selection import  train_test_split
X=df.drop(["ProdTaken"], axis=1)
y=df["ProdTaken"]

In [31]:
X.head()

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisitors
0,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [32]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: ProdTaken, dtype: int64

In [33]:
y.value_counts()
# Bagging and boosting works good in unbalanced datasets.

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [34]:
# Train test split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [35]:
# Contains all object type 
cat_features=X.select_dtypes("object").columns.tolist()
cat_features

['TypeofContact',
 'Occupation',
 'Gender',
 'ProductPitched',
 'MaritalStatus',
 'Designation']

In [36]:
# Get total number of numeric Features:
num_features=X.select_dtypes(exclude="object").columns.tolist()
num_features

['Age',
 'CityTier',
 'DurationOfPitch',
 'NumberOfFollowups',
 'PreferredPropertyStar',
 'NumberOfTrips',
 'Passport',
 'PitchSatisfactionScore',
 'OwnCar',
 'MonthlyIncome',
 'TotalVisitors']

In [37]:
from sklearn.preprocessing import  OneHotEncoder, StandardScaler
from sklearn.compose import  ColumnTransformer

# OHE is for categorical features
# Standard Scaler is for scaling down data in same scale (although not necessary here)
# Column Transformer helps to build a pipeline to apply multiple transformations.

numeric_transformer= StandardScaler()
oh_transformer = OneHotEncoder(drop="first") # As to represet 3 features, 2 columns is enough

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoding", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features )
    ]
)

In [38]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoding', OneHotEncoder(drop='first'),
                                 ['TypeofContact', 'Occupation', 'Gender',
                                  'ProductPitched', 'MaritalStatus',
                                  'Designation']),
                                ('StandardScaler', StandardScaler(),
                                 ['Age', 'CityTier', 'DurationOfPitch',
                                  'NumberOfFollowups', 'PreferredPropertyStar',
                                  'NumberOfTrips', 'Passport',
                                  'PitchSatisfactionScore', 'OwnCar',
                                  'MonthlyIncome', 'TotalVisitors'])])

In [39]:
## applying fit_transform for training dataset

X_train = preprocessor.fit_transform(X_train)

In [40]:
# X_train.head() not a dataframe
pd.DataFrame(X_train).head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.7214,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,0.679690,0.782966,-0.382245,-0.774151
1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.7214,0.690023,0.282777,-0.725271,1.511598,-0.632399,0.679690,0.782966,-0.459799,0.643615
2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.7214,-1.020350,0.282777,1.771041,0.418708,-0.632399,0.679690,0.782966,-0.245196,-0.065268
3,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,-0.7214,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,1.408395,-1.277194,0.213475,-0.065268
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.7214,2.400396,-1.720227,-0.725271,1.511598,-0.632399,-0.049015,-1.277194,-0.024889,2.061382

In [41]:
# Apply same transformation for X_test

X_test = preprocessor.transform(X_test)

## 7. Apply Random Forest Classifier, DecisionTreeClassifier and Gradient Boosting Classifier

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import  DecisionTreeClassifier
from sklearn.ensemble import  GradientBoostingClassifier
from sklearn.metrics import accuracy_score,classification_report,ConfusionMatrixDisplay,precision_score,recall_score,f1_score,roc_auc_score,roc_curve

In [43]:
models = { "Decision Tree":DecisionTreeClassifier() ,
"Random Forst" : RandomForestClassifier(),
"Gradient Boost": GradientBoostingClassifier()}

In [44]:
list(models)

['Decision Tree', 'Random Forst', 'Gradient Boost']

In [45]:
print("\n")
for i in range(len(list(models))):
    model= list(models.values())[i]
    model.fit(X_train,y_train)

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Training set accuracy
    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1=f1_score(y_train,y_train_pred, average="weighted")
    model_train_precision=precision_score(y_train,y_train_pred)
    model_train_recall=recall_score(y_train,y_train_pred)
    model_train_rocauc_score=roc_auc_score(y_train,y_train_pred)


    # Testing set accuracy
    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1=f1_score(y_test,y_test_pred, average="weighted")
    model_test_precision=precision_score(y_test,y_test_pred)
    model_test_recall=recall_score(y_test,y_test_pred)
    model_test_rocauc_score=roc_auc_score(y_test,y_test_pred)



    print(list(models.keys())[i])

    print("Model Training Performance Set")
    print("- Accuracy: ", round(model_train_accuracy,3) )
    print("- F1 Score: ", round(model_train_f1,3) )
    print("- Precision: ", round(model_train_precision,3) )
    print("- Recall: ", round(model_train_recall,3) )


    print("-----------------------------------------------------------")

    print("Model Testing Performance Set")
    print("- Accuracy: ", round(model_test_accuracy,3) )
    print("- F1 Score: ", round(model_test_f1,3) )
    print("- Precision: ", round(model_test_precision,3) )
    print("- Recall: ", round(model_test_recall,3) )



    print("="*35)
    print("\n")

Decision Tree
Model Training Performance Set
- Accuracy:  1.0
- F1 Score:  1.0
- Precision:  1.0
- Recall:  1.0
-----------------------------------------------------------
Model Testing Performance Set
- Accuracy:  0.916
- F1 Score:  0.915
- Precision:  0.804
- Recall:  0.754
===================================

Random Forst
Model Training Performance Set
- Accuracy:  1.0
- F1 Score:  1.0
- Precision:  1.0
- Recall:  1.0
-----------------------------------------------------------
Model Testing Performance Set
- Accuracy:  0.93
- F1 Score:  0.925
- Precision:  0.962
- Recall:  0.67
===================================


Gradient Boost
Model Training Performance Set
- Accuracy:  0.894
- F1 Score:  0.882
- Precision:  0.876
- Recall:  0.502
-----------------------------------------------------------
Model Testing Performance Set
- Accuracy:  0.859
- F1 Score:  0.84
- Precision:  0.773
- Recall:  0.393
===================================

## 8. Hyper Parameter tuning

In [46]:
# Hyper Parameter Tuning:
rf_params = {
    "max_depth":[5,8,15,None,10],
    "max_features": [5,7,"auto",8],
    "min_samples_split": [2,8,15,20],
    "n_estimators": [100,200,500,1000]
}

dt_params={
    'criterion':["gini","entropy","log_loss"],
    'splitter':["best","random"],
    'max_depth':[5,8,15,10],
    'max_features':["auto","sqrt","log2"]
    }

gradient_params={
    "loss":["log_loss","deviance","exponential"],
    'criterion':["friedman_mse","squared_error","mse"],
    "min_samples_split": [2,8,15,20],
    "n_estimators": [100,200,500,1000],
    'max_depth':[5,8,15,None,10],
}

In [47]:
randomcv_models = [("RF",RandomForestClassifier(),rf_params),
                    ("DT",DecisionTreeClassifier(),dt_params),
                    ("GB", GradientBoostingClassifier(),gradient_params )]

####  More models = More Time Taken; RF is bttr as we deduced from random_forest_classifier, so we will remove DT

In [48]:
randomcv_models = [("RF",RandomForestClassifier(),rf_params),
                    ("GB", GradientBoostingClassifier(),gradient_params )]

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
model_param={}

for name,model,param in randomcv_models:
    random=RandomizedSearchCV(estimator=model,param_distributions=param,n_iter=100,cv=3,verbose=2,n_jobs=-1)

    random.fit(X_train,y_train)

    model_param[name] = random.best_params_

In [50]:
for model_name in model_param:
    print(f"------------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

## 9. Retraining

In [51]:
models = { "Random Forest" : RandomForestClassifier(n_estimators= 500, min_samples_split= 2, max_features= 7, max_depth= None),
 "Gradient Boosting" : GradientBoostingClassifier(n_estimators= 200, min_samples_split= 15,max_depth=None, loss= 'exponential', criterion= 'friedman_mse')}

In [52]:
print("\n")
for i in range(len(list(models))):
    model= list(models.values())[i]
    model.fit(X_train,y_train)

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Training set accuracy
    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1=f1_score(y_train,y_train_pred, average="weighted")
    model_train_precision=precision_score(y_train,y_train_pred)
    model_train_recall=recall_score(y_train,y_train_pred)
    model_train_rocauc_score=roc_auc_score(y_train,y_train_pred)


    # Testing set accuracy
    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1=f1_score(y_test,y_test_pred, average="weighted")
    model_test_precision=precision_score(y_test,y_test_pred)
    model_test_recall=recall_score(y_test,y_test_pred)
    model_test_rocauc_score=roc_auc_score(y_test,y_test_pred)



    print(list(models.keys())[i])

    print("Model Training Performance Set")
    print("- Accuracy: ", round(model_train_accuracy,3) )
    print("- F1 Score: ", round(model_train_f1,3) )
    print("- Precision: ", round(model_train_precision,3) )
    print("- Recall: ", round(model_train_recall,3) )


    print("-----------------------------------------------------------")

    print("Model Testing Performance Set")
    print("- Accuracy: ", round(model_test_accuracy,3) )
    print("- F1 Score: ", round(model_test_f1,3) )
    print("- Precision: ", round(model_test_precision,3) )
    print("- Recall: ", round(model_test_recall,3) )



    print("="*35)
    print("\n")

Random Forest
Model Training Performance Set
- Accuracy:  1.0
- F1 Score:  1.0
- Precision:  1.0
- Recall:  1.0
-----------------------------------------------------------
Model Testing Performance Set
- Accuracy:  0.931
- F1 Score:  0.927
- Precision:  0.963
- Recall:  0.675
===================================


Gradient Boosting
Model Training Performance Set
- Accuracy:  1.0
- F1 Score:  1.0
- Precision:  1.0
- Recall:  1.0
-----------------------------------------------------------
Model Testing Performance Set
- Accuracy:  0.955
- F1 Score:  0.953
- Precision:  0.962
- Recall:  0.801
===================================

### We can See Significant Performace Improvement Especially Recall and Accuracy of GB wrt RF